version: '3.7'

services:
  dockerMongo:
    image: mongo:latest
    ports:
    - 27017:27017
    
  dockerRedis:
    image: redis:latest
    ports:
    - 6379:6379
     
  app:
    image: customer-crud
    ports:
    - 8080:8080
    links:
    - dockerRedis
    - dockerMongo